### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [Simplex-Dev/QuickConnectButton#20]
java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.minecraft.client.gui.screen.TitleScreen.handler$fpk000$addCustomButton(TitleScreen:3047)
	at net.minecraft.client.gui.screen.TitleScreen.initWidgetsNormal(TitleScreen:171)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen:130)
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen:392)
	at net.minecraft.client.gui.screen.Screen.init(Screen:383)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1049)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:673)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sternschnaube** [comment]
Thank you.
