### ISSUE TITLE
Running in 1.16 without Java 16 causes crash

### ISSUE THREAD

**Issue by OroArmor** [Simplex-Dev/QuickConnectButton#4]
```
Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config quickconnectbutton.mixins.json
    at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
    at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
    at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
    at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44)
    at net.fabricmc.loader.launch.common.FabricMixinBootstrap$$Lambda$69/1409545055.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported
    at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1493)
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:494)
    at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:463)
    at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:392)
    at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1093)
    at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
 ```
 Just compile with Java 8 and set the mixin version to `JAVA_8` as well

**Comment by mounderfod** [comment]
Fixed in #3.
